add_newline = true

# Replace the "❯" symbol in the prompt
[character]
symbol = "  $"
use_symbol_for_status = false
style_success = "blue"
style_failure = "red"

# Disable the package module, hiding it from the prompt completely
[package]
style = "dimmed red"

[cmd_duration]
min_time = 4
style = "dimmed green"

[directory]
truncation_length = 0
truncate_to_repo = false
style = "blue"

[git_branch]
style = "purple"

[git_status]
style = "dimmed red"

[rust]
style = "dimmed red"
