#!/usr/bin/env bash

function get-id {
  rg 'Jack\S+ AirPods Pro' <&0 |
    rg -o '^address: [^,]+' |
    rg -o '\S+$'
}

declare -r ACTION=$(
  if [[ "$1" == '-d' || "$1" == '--disconnect' ]]; then
    echo '--disconnect'
  else
    echo '--connect'
  fi
)

declare -r NUM_DEVICES=$(blueutil --recent | get-id | wc -l)
if [[ "$NUM_DEVICES" != 1 ]]; then
  echo "Expected 1 device but found $NUM_DEVICES." >&2
  exit 1
fi

if [[ "$ACTION" == "--connect" &&
      $(blueutil --paired | rg -v 'not connected' | get-id | wc -l) != 0 ]]; then
  echo 'Already paired.' >&2
  exit
fi

declare -r DEVICE_ID=$(blueutil --recent | get-id)

echo "Performing $ACTION..."
blueutil "$ACTION" "$DEVICE_ID"
