#!/usr/bin/env bash

declare -r FILEPATH="$1"

if rg -q '\.rs$' <<< "$FILEPATH"; then
  cargo fmt
elif rg -q '\.(cpp|hpp)$' <<< "$FILEPATH"; then
  clang-format -i "$FILEPATH"
elif rg -q '\.hs$' <<< "$FILEPATH"; then
  brittany --write-mode=inplace "$FILEPATH"
fi

trim --in-place "$FILEPATH"

echo
date
