#!/usr/bin/env bash

function finish {
    echo
    date
}
trap finish EXIT

# consts
declare -r FILEPATH="$1"
declare -r GIT_ROOT=$(git rev-parse --show-toplevel 2> /dev/null)

#
if [[ -d "$GIT_ROOT" ]]; then
    cd "$GIT_ROOT"

    if [[ -f 'Cargo.toml' ]]; then # rg -q '\.rs$' <<< "$FILEPATH"; then
        ( 
            set -x; 
            cargo fmt ||
               rustfmt --emit files "$FILEPATH";
            echo && date
        )
    elif rg -q '\.(cpp|hpp)$' <<< "$FILEPATH"; then
        ( set -x; clang-format -i "$FILEPATH"; echo && date )
    elif rg -q '\.hs$' <<< "$FILEPATH"; then
        ( set -x; brittany --write-mode=inplace "$FILEPATH"; echo && date )
    elif rg -q '\.json$' <<< "$FILEPATH"; then
        ( set -x; jq . --sort-keys < "$FILEPATH" | pbcopy && pbpaste > "$FILEPATH" )
    else
        ( set -x; trim --in-place "$FILEPATH"; echo && date )
    fi
else
    echo "'$(pwd)' is not a git repo... exiting..." >&2
    exit 1
fi

