#!/usr/bin/env bash

declare -r FILEPATH="$1"

if [[ -f 'Cargo.toml' ]]; then
  time cargo run --color always; echo && date
elif [[ -f 'stack.yaml' ]]; then
  time stack run; echo && date
else
  time "$FILEPATH"; echo && date
fi
