#!/usr/bin/env bash

declare -r FILEPATH="$1"

if rg -q '\.rs$' <<< "$FILEPATH"; then
  cargo fmt; echo && date
elif rg -q '\.(cpp|hpp)$' <<< "$FILEPATH"; then
  clang-format -i "$FILEPATH"; echo && date
elif rg -q '\.hs$' <<< "$FILEPATH"; then
  brittany --write-mode=inplace "$FILEPATH"; echo && date
else
  trim --in-place "$FILEPATH"; echo && date
fi
