#!/usr/bin/env bash

declare -r FILEPATH="$1"

if [[ -f 'Cargo.toml' ]]; then
    ( set -x; time cargo test --color always; echo && date )
elif [[ -f 'stack.yaml' ]]; then
    ( set -x; time stack test; echo && date )
fi
