#!/usr/bin/env bash

declare -r FILEPATH="$1"

if [[ -f 'Cargo.toml' ]]; then
  time cargo check --color always; echo && date
elif [[ -f 'Makefile' ]]; then
  time make --print-directory; echo && date
elif [[ -f 'stack.yaml' ]]; then
  time stack build; echo && date
fi
