#!/usr/bin/env bash

declare -r FILEPATH="$1"

if [[ -f 'Cargo.toml' ]] && rg -q '\.rs$' <<< "$FILEPATH"; then
    ( set -x; time cargo run --color always; echo && date )
elif [[ -f 'stack.yaml' ]] && rg -q '\.hs$' <<< "$FILEPATH"; then
    ( set -x; time stack run; echo && date )
else
    time "$FILEPATH"; echo && date
fi
