#!/usr/bin/env bash

declare -r FILEPATH="$1"

if [[ -f 'Cargo.toml' ]]; then
  time cargo test --color always; echo && date
elif [[ -f 'stack.yaml' ]]; then
  time stack test; echo && date
fi 2>&1 |
  less --RAW-CONTROL-CHARS
