#!/usr/bin/env bash

declare -r COUNT=$(
  if rg -q '^\d+$' <<< "$1"; then
    echo "$1"
  else
    echo '128'
  fi
)

#
openssl rand -base64 "$(( $COUNT * 2))" |
  tr --delete --complement '[:alnum:]' |
  head -c "$COUNT"
