#!/usr/bin/env bash

function get {
  declare -r COORDS="$1"
  declare -r DATE=$(date +'%Y-%m-%d')
  open "https://darksky.net/details/$COORDS/$DATE/us12/en"
}


# fayetteville
get '43.0307,-76.0036'

# kendall
get '42.3622,-71.0842'
