#!/usr/bin/env bash

declare -r LITTLE_FERRY='40.849,-74.0375'

{
  echo "https://darksky.net/forecast/$LITTLE_FERRY/us12/en"
  echo "https://darksky.net/details/$LITTLE_FERRY/$(date +'%m-%d-%y')/us12/en"
} |
  xargs open -a 'Brave Browser'
