tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Download with resuming and segmented downloading
brew "aria2"
# Spell checker with better logic than ispell
brew "aspell"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# New way to see and navigate directory trees
brew "broot"
# Command-line interface for SQLite
brew "sqlite"
# General-purpose data compression with high compression ratio
brew "xz"
# Interpreted, interactive, object-oriented programming language
brew "python", link: false
# Control Google Chrome from the command-line
brew "chrome-cli"
# Anti-virus software
brew "clamav"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# Color-highlighted diff(1) output
brew "colordiff"
# GNU File, Shell, and Text utilities
brew "coreutils"
# More intuitive version of du in rust
brew "dust"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Fully featured Firefox Send client
brew "ffsend"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# WebDriver <-> Marionette proxy
brew "geckodriver"
# Glorious Glasgow Haskell Compilation System
brew "ghc"
# Distributed revision control system
brew "git"
# Command-line option parsing utility
brew "gnu-getopt"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# GNU implementation of time utility
brew "gnu-time"
# GNU implementation of which utility
brew "gnu-which"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# GNU grep, egrep and fgrep
brew "grep"
# GitHub Markdown previewer
brew "grip"
# Popular GNU data compression program
brew "gzip"
# The Haskell Tool Stack
brew "haskell-stack"
# Text-based UI library
brew "ncurses"
# Improved top (interactive process viewer)
brew "htop"
# Command-line benchmarking tool
brew "hyperfine"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Utility to optimize JPEG files
brew "jpegoptim"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Platform built on V8 to build network applications
brew "node"
# Interactive environments for writing and running code
brew "jupyterlab"
# Pager program similar to more
brew "less"
# Utility for directing compilation
brew "make"
# Create modern online books from Markdown files
brew "mdbook"
# Show markdown documents on text terminals
brew "mdcat"
# NCurses Disk Usage
brew "ncdu"
# Realtime console network usage monitor
brew "nload"
# Multithreaded PNG optimizer written in Rust
brew "oxipng"
# Shell command parallelization utility
brew "parallel"
# Parallel gzip
brew "pigz"
# Parallel, indexed, xz compressor
brew "pixz"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# The Rust toolchain installer
brew "rustup-init"
# Build tool for Scala projects
brew "sbt"
# JVM-based programming language
brew "scala"
# Intuitive find & replace CLI
brew "sd"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Fuzzy Finder in rust!
brew "sk"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Statistics from the command-line
brew "st"
# The cross-shell prompt for astronauts
brew "starship"
# Code-search similar to ack
brew "the_silver_searcher"
# Granddaddy of HTML tools, with support for modern standards
brew "tidy-html5"
# Script to convert text to title case
brew "titlecase"
# Terminal multiplexer
brew "tmux"
# Program that allows you to count code, quickly
brew "tokei"
# Anonymizing overlay network for TCP
brew "tor"
# Use SOCKS-friendly applications with Tor
brew "torsocks"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extraction utility for .zip compressed archives
brew "unzip"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# Download YouTube videos from the command-line
brew "youtube-dl"
# Compression and file packaging/archive utility
brew "zip"
# Zstandard is a real-time compression algorithm
brew "zstd"
cask "1password"
cask "aerial"
cask "alacritty"
cask "atom"
cask "brave-browser"
cask "brooklyn"
cask "discord"
cask "firefox"
cask "font-fira-code"
cask "font-inconsolata"
cask "google-chrome"
cask "java"
cask "mactex-no-gui"
cask "phantomjs"
cask "protonvpn"
cask "signal"
cask "tor-browser"
cask "tresorit"
cask "wire"
cask "wkhtmltopdf"
